name: Validate MPE changes 

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of MPE Management terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: azurenoops/terraform-github-actions/terraform-fmt-check@v1.34.2
        with:
          path: src

  validate:
    runs-on: ubuntu-latest
    name: Validate MPE Management terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: azurenoops/terraform-github-actions/terraform-validate@v1.34.2
        with:
          path: src